time ../Code/bin/EstimateEyeAndStem -p ./processed/001 -i 001.PNG > ./processed/001.txt 
time ../Code/bin/EstimateEyeAndStem -p ./processed/002 -i 002.PNG > ./processed/002.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/003 -i 003.PNG > ./processed/003.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/004 -i 004.PNG > ./processed/004.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/005 -i 005.PNG > ./processed/005.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/006 -i 006.PNG > ./processed/006.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/007 -i 007.PNG > ./processed/007.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/008 -i 008.PNG > ./processed/008.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/009 -i 009.PNG > ./processed/009.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/010 -i 010.PNG > ./processed/010.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/011 -i 011.PNG > ./processed/011.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/012 -i 012.PNG > ./processed/012.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/013 -i 013.PNG > ./processed/013.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/014 -i 014.PNG > ./processed/014.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/015 -i 015.PNG > ./processed/015.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/016 -i 016.PNG > ./processed/016.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/017 -i 017.PNG > ./processed/017.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/018 -i 018.PNG > ./processed/018.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/019 -i 019.PNG > ./processed/019.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/020 -i 020.PNG > ./processed/020.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/021 -i 021.PNG > ./processed/021.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/022 -i 022.PNG > ./processed/022.txt
time ../Code/bin/EstimateEyeAndStem -p ./processed/023 -i 023.PNG > ./processed/023.txt

awk  '/Estimated optic nerve width: /{print $NF}' processed/*.txt
